apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-angular-spa-template-dev

resources:
  - ../../base

# Single replica and a dev image tag for local/dev clusters.
replicas:
  - name: server
    count: 1

images:
  - name: go-angular-spa-template
    newTag: dev

patches:
  - target:
      kind: ConfigMap
      name: server-config
    patch: |-
      - op: replace
        path: /data/APP_ENVIRONMENT
        value: "development"
      - op: replace
        path: /data/LOG_LEVEL
        value: "debug"
      - op: replace
        path: /data/DB_SSL_MODE
        value: "disable"
